### ISSUE TITLE
NPCc get stucked in the ranged fight after Load Saved Game 

### ISSUE THREAD

**Issue by pawbuj1981** [AmProsius/gothic-1-community-patch#196]
**Describe the bug**
As in title NPCc get stucked in the ranged fight after Load Saved Game 

**Expected behavior**
NPCc should attack hero without any interruption after Load Saved Game. 

**Steps to reproduce the issue**
1.  Attack the hero and allow NPC to use ranged weapon.
2.  Save Game and then Load.
3.  NPC get stucked handling ranged weapon. 

**Additional context**

**Comment by pawbuj1981** [comment]
I did not found solution in any patch/mod for G1. It must be deep engine issue.

**Comment by N1kX94** [comment]
This is fixed in the Gothic Mod Fix. This part in zs_attack should help
```
***
	// DEBUG! Загрузка сохранения, сделанного во время атаки с использованием стрелкового оружия или магической атаки.
	// В этом случае убирание оружия или деактивация заклинания позволяют избежать зависания в состоянии атаки.
	if(!Hlp_IsValidNpc(other))
	{
		if(Npc_IsInFightMode(self,FMODE_FAR))
		{
			AI_RemoveWeapon(self);
		}
		
		else if(Npc_IsInFightMode(self,FMODE_MAGIC))
		{
			AI_UnreadySpell(self);
		};
	};
***
```

**Comment by pawbuj1981** [comment]
@N1kX94 I have tested with Gothic Mod Fix latest version and the bug still occurs. So the code might not help to solve mentioned issue .

**Comment by szapp** [comment]
If the solution suggested is not working, one could hook the unarchiver function of NPCs to reset the stance.
